import type { Metadata } from "next";
// Next.js에서 제공하는 Google Font 최적화 기능을 사용하여 폰트를 불러올 수 있습니다.
// import { Geist } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";

// Google Font 최적화 기능예제.
// const geistSans = Geist({
//   variable: "--font-geist-sans", // CSS 변수로 사용할 이름을 지정합니다.
//   subsets: ["latin"], // 사용할 문자 집합을 지정합니다. 예: latin, cyrillic, greek 등
// });

// 브라우저 내 페이지의 메타데이터를 설정하는 객체입니다. title과 description을 포함하여 페이지의 제목과 설명을 정의합니다.
export const metadata: Metadata = {
  title: {
    template: "%s | Next.js Practice", // 페이지 제목의 템플릿을 정의합니다. %s는 각 페이지의 제목으로 대체됩니다.
    default: "Next.js Practice", // 페이지 제목이 명시적으로 설정되지 않은 경우 사용할 기본 제목입니다.
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={"h-full antialiased"}
    >
      <body className="min-h-full flex flex-col">
        <Navigation />
        {children}
      </body>
    </html>
  );
}
